### ISSUE TITLE
Is inference on perhiperal instead of central viable?

### ISSUE THREAD

**Issue by teover** [metanav/AdvancedWearables#1]
Hi, I found interest in this project as I would like to achieve something similar.

Is there any reason why inference is done on the central instead of the perhiperal?
It would be more efficient to only send results from inference instead of all the accelerometer data.

Best Regards, 
Tor

**Comment by metanav** [comment]
Hi @teover,

Thanks for showing interest in the project. You can do the inferencing on the peripheral device and I agree it would be more efficient. In my case, I have to display the accelerometer data on the LCD and store it on the SD card attached to the central device during data collection. Also, I wanted to do sensor fusion with other peripheral devices in a future project so I chose this design.

**Comment by teover** [comment]
Thank you for clarifying, I will explore this project further then. Good luck with your future projects!

**Comment by metanav** [comment]
By the way you can find the project write-up here: https://www.hackster.io/naveenbskumar/posture-watchdog-c03f77
